/*
 * DKAM Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0-dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/GIT_USER_ID/GIT_REPO_ID/dbpackage"
	// "github.com/amitc481/health_check/dbpackage"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
	// openapi "github.com/amitc481/health_check/go"
)

func main() {
	log.Printf("Server started")

	HealthCheckAPIService := openapi.NewHealthCheckAPIService()
	HealthCheckAPIController := openapi.NewHealthCheckAPIController(HealthCheckAPIService)

	router := openapi.NewRouter(HealthCheckAPIController)

	dbpackage.DbConnect()

	log.Fatal(http.ListenAndServe(":4801", router))
}
