/*
 * DKAM Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0-dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ProblemDetails - A problem detail to carry a message in a HTTP error response.
type ProblemDetails struct {

	// Contains detailed information about the problem, such as its source data that can be used for debugging purposes.
	Message string `json:"message,omitempty"`
}

// AssertProblemDetailsRequired checks if the required fields are not zero-ed
func AssertProblemDetailsRequired(obj ProblemDetails) error {
	return nil
}

// AssertProblemDetailsConstraints checks if the values respects the defined constraints
func AssertProblemDetailsConstraints(obj ProblemDetails) error {
	return nil
}
