/*
 * DKAM Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0-dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Id struct {

	// The unique ID of the resource, prefixed with one of the allowed prefixes (e.g., 'pro-123e4567-f89a-72d3-a456-426614174021', 'health_check-342e4567-e89b-16d3-a456-326614174543', 'mod-783e4567-e89b-12a3-a443-566614174456').
	Id string `json:"id,omitempty"`
}

// AssertIdRequired checks if the required fields are not zero-ed
func AssertIdRequired(obj Id) error {
	return nil
}

// AssertIdConstraints checks if the values respects the defined constraints
func AssertIdConstraints(obj Id) error {
	return nil
}
